name: puremood_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+5
  record: ^6.1.2
  record_linux: ^1.2.1
  just_audio: ^0.9.35
  permission_handler: ^11.0.1
  fl_chart: ^1.1.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  table_calendar: ^3.0.9

  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.4

  flutter_local_notifications: ^19.5.0
  provider: ^6.1.2
  flutter_stripe: ^10.0.0
 # confetti: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # إذا عندك صور تضيفها هنا
  # assets:
  #   - images/
